titile: gotolee的博客
email: zimu94@163.com
keyword: "gotolee, gotolee的博客, gotolee Python blog"
url: "http://gotolee.github.io"         
baseurl: ""   
github_repo: "https://github.com/gotolee/gotolee.github.io.git"

github_username: gotolee

permalink: pretty
paginate: 10
Regeneration: true 
plugins: [jekyll-paginate]

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important

# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# Friends
friends: [
    {
        title: "GitHub·gotolee",
        href: "http://gotolee.github.io"
    }
]
